# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: movie.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='movie.proto',
  package='redisData',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x0bmovie.proto\x12\tredisData\"\x1e\n\x0cMovieRequest\x12\x0e\n\x06userId\x18\x01 \x01(\t\"X\n\nMovieReply\x12\x11\n\tmovieList\x18\x01 \x01(\t\x12\x13\n\x0buserDislike\x18\x02 \x01(\t\x12\x10\n\x08userLike\x18\x03 \x01(\t\x12\x10\n\x08movieMod\x18\x04 \x01(\t2G\n\x07Greeter\x12<\n\x08getMovie\x12\x17.redisData.MovieRequest\x1a\x15.redisData.MovieReply\"\x00\x62\x06proto3'
)




_MOVIEREQUEST = _descriptor.Descriptor(
  name='MovieRequest',
  full_name='redisData.MovieRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='userId', full_name='redisData.MovieRequest.userId', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=26,
  serialized_end=56,
)


_MOVIEREPLY = _descriptor.Descriptor(
  name='MovieReply',
  full_name='redisData.MovieReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='movieList', full_name='redisData.MovieReply.movieList', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='userDislike', full_name='redisData.MovieReply.userDislike', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='userLike', full_name='redisData.MovieReply.userLike', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='movieMod', full_name='redisData.MovieReply.movieMod', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=58,
  serialized_end=146,
)

DESCRIPTOR.message_types_by_name['MovieRequest'] = _MOVIEREQUEST
DESCRIPTOR.message_types_by_name['MovieReply'] = _MOVIEREPLY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

MovieRequest = _reflection.GeneratedProtocolMessageType('MovieRequest', (_message.Message,), {
  'DESCRIPTOR' : _MOVIEREQUEST,
  '__module__' : 'movie_pb2'
  # @@protoc_insertion_point(class_scope:redisData.MovieRequest)
  })
_sym_db.RegisterMessage(MovieRequest)

MovieReply = _reflection.GeneratedProtocolMessageType('MovieReply', (_message.Message,), {
  'DESCRIPTOR' : _MOVIEREPLY,
  '__module__' : 'movie_pb2'
  # @@protoc_insertion_point(class_scope:redisData.MovieReply)
  })
_sym_db.RegisterMessage(MovieReply)



_GREETER = _descriptor.ServiceDescriptor(
  name='Greeter',
  full_name='redisData.Greeter',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=148,
  serialized_end=219,
  methods=[
  _descriptor.MethodDescriptor(
    name='getMovie',
    full_name='redisData.Greeter.getMovie',
    index=0,
    containing_service=None,
    input_type=_MOVIEREQUEST,
    output_type=_MOVIEREPLY,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_GREETER)

DESCRIPTOR.services_by_name['Greeter'] = _GREETER

# @@protoc_insertion_point(module_scope)
